-- INITIAL DATA ABOUT ALL COUNTRIES
# INSERT INTO country(country_code,name,continent,currency,language) VALUES ();
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AD","Andorra","Europe","Andorra la Vella","Euro","Catalan","Roman Catholicizm","Constitutional monarchy","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AE","United Arab Emirates","Asia","Abu Dhabi","Dirham","Arabic","Islam","Constitutional and elective monarchy","UTC+4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AF","Afghanistan","Asia","Kabul","Dari and Pashto","Afgani","Islam","Islamic Republic","UTC+4:30");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AG","Antigua and Barbuda","North America", "St. John''s","East Caribbean dollar","English","Christian","Constitutional monarchy","UTC-4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AI","Anguilla","North America","The Valley","East Caribbean dollar","English","Protestantism","Monarchy","UTC-4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AL","Albania","Europe","Tirana","Lek","Albanian","Islam","Republic","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AM","Armenia","Europe","Yerevan","Dram","Armenian","Christianity","Republic","UTC+4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AO","Angola","Africa","Luanda","Kwanza","Portuguese","Christianity","Republic","UTC+1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AQ","Antarctica","Antarctica","Everywhere you want","Food","Roarrrrr","Freedom","Anarchy","UTC0");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AR","Argentina","South America","Buenos Aires","Peso","Spanish","Catholicism","Republic","UTC-3");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AS","American Samoa","Oceania","Pago Pago","United States dollar","English and Samoan","Protestantism","Non-incorporated territory of the USA","UTC-11");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AT","Austria","Europe","Vienna","Euro","German","Catholicism","Federal parliamentary republic","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AU","Australia","Oceania","Canberra","Australian dollar","English","Various","Federal parliamentary constitutional monarchy","UTC+8;UTC+9.5;UTC+10");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AW","Aruba","North America","Oranjestad","Aruban florin","Dutch and Papiamento","Catholicism","Autonomous country within the Kingdom of the Netherlands","UTC-4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AX","Aland Islands","Europe","Mariehamn","Euro","Swedish","Lutheranism","Devolved parliamentary autonomous region","UTC+2");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("AZ","Azerbaijan","Asia","Baku","Manat","Azerbaijani","Islam","Republic","UTC+4(winter)/UTC+5(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BA","Bosnia and Herzegovina","Europe","Sarajevo","Convertible mark","Bosnian","Christianity and Islam","Federal parliamentary constitutional republic","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BB","Barbados","North America","Bridgetown","Barbadian dollar","English and Bajan Creole","Christianity","Constitutional monarchy","UTC−4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BD","Bangladesh","Asia","Dhaka","Bangladeshi taka","Bengali","Islam","Unitary parliamentary constitutional republic","UTC+6");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BE","Belgium","Europe","Brussels","Euro","Dutch, French and German","Christianity","Constitutional monarchy","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BF","Burkina Faso","Africa","Ouagadougou","West African CFA franc","French","Christianity, Islam and Animism","Republic","UTC0");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BG","Bulgaria","Europe","Sofia","Lev","Bulgarian","Orthodox","Parliamentary republic","UTC+2(winter)/UTC+3(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BH","Bahrain","Asia","Manama","Bahraini dinar","Arabic","Islam","Unitary parliamentary constitutional monarchy","UTC+3");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BI","Burundi","Africa","Gitega, Bujumbura","Burundian franc","Kirundi, French and English","Catholicism","Republic","UTC+2");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BJ","Benin","Africa","Porto-Novo","West African CFA franc","French","Catholicism and Islam","Republic","UTC+1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BL","Saint Barthelemy","North America","Gustavia","Euro","French","Catholicism","Devolved parliamentary dependency","UTC-4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BM","Bermuda","North America","Hamilton","Bermudian dollar","English","Protestant","Parliamentary dependency under a constitutional monarchy","UTC-3(winter)/UTC-4(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BN","Brunei Darussalam","Asia","Bandar Seri Begawan","Brunei dollar","Malay and English","Sunni Islam","Unitary Islamic absolute monarchy","UTC+8");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BO","Bolivia, Plurinational State of Bolivia","South America","Sucre","Boliviano","Spanish","Catholicism","Republic","UTC-4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BQ","Bonaire, Sint Eustatius and Saba","North America","-","United States dollar","Dutch","-","Constitutional monarchy","UTC−4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BR","Brazil","South America","Brasília","Real","Portuguese","Catholicism","Federal presidential constitutional republic","UTC(−2 to -5)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BS","Bahamas","North America","Nassau","Bahamian dollar","English","Protestant","Unitary parliamentary constitutional monarchy","UTC-5(winter)/UTC-4(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BT","Bhutan","Asia","Thimphu","Ngultrum","Dzongkha","Vajrayana Buddhism","Constitutional monarchy","UTC+06");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BV","Bouvet Island","Antarctica","-","Norwegian krone","Norwegian","Church of Norway","Dependency under a constitutional monarchy","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BW","Botswana","Africa","Gaborone","Botswana pula","English and Setswana","Christianity","Republic","UTC+2");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BY","Belarus","Europe","Minsk","Belarusian ruble","Belarusian and Russian","Orthodoxy","Unitary presidential republic","UTC+3");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("BZ","Belize","North America","Belmopan","Belize dollar","English","Christianity","Unitary parliamentary constitutional monarchy","UTC−6");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CA","Canada","North America","Ottawa","Canadian dollar","English and French","Christianity","Federal parliamentary constitutional monarchy","UTC-3.5/-8(winter)/UTC-2.5/-7(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CC","Cocos (Keeling) Islands","Asia","West Island","Australian dollar","Malay","Islam","Directly administered dependency","UTC+06:30");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CD","Congo, the Democratic Republic of the Congo","Africa","Kinshasa","Congolese franc","French","Catholicism","Unitary semi-presidential constitutional republic","UTC+1/+2");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CF","Central African Republic","Africa","Bangui","Central African CFA franc","French and Sango","Protestants","Unitary semi-presidential constitutional republic","UTC+1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CG","Congo","Africa","Brazzaville","Central African CFA franc","French","Christianity","Republic","UTC+1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CH","Switzerland","Europe","Bern","Swiss franc","German, French, Italian and Romansh","Catholicism and Protestant","Federal semi-direct democracy","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CI","Cote d'Ivoire","Africa","Yamoussoukro","West African CFA franc","French","Islam","Republic","UTC+0");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CK","Cook Islands","Oceania","Avarua","Cook Islands dollar and New Zealand dollar ","English and Cook Islands Māori","Protestants","Unitary constitutional monarchy","UTC-10");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CL","Chile","South America","Santiago","Peso (CLP)","Spanish","Catholicism","Unitary presidential constitutional republic","UTC−3 and -5");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CM","Cameroon","Africa","Yaoundé","Central African CFA franc","English and French","Catholicism and Protestant","Republic","UTC+1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CN","China","Asia","Beijing","Renminbi","Chinese","Shenism","One-party socialist republic","UTC+8");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CO","Colombia","South America","Bogotá","Peso(COP)","Spanish","Catholicism","Unitary presidential constitutional republic","UTC−5");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CR","Costa Rica","North America","San José","Costa Rican colón","Spanish","Christianity","Unitary presidential constitutional republic","UTC−6");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CU","Cuba","North America","Havana","Peso(CUP) and Convertible pesoa(CUC)","Spanish","Christianity","One-party socialist republic","UTC-5(winter)/UTC-4(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CV","Cape Verde","Africa","Praia","Cape Verdean escudo(CVE)","Portuguese","Christianity","Unitary semi-presidential republic","UTC-1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CW","Curacao","North America","Willemstad","Netherlands Antillean guilder","Papiamentu, Dutch and English","Catholicism","Constitutional monarchy","UTC-4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CX","Christmas Island","Asia","Flying Fish Cove","Australian dollar","Mandarin and English","Islam and Buddhism","Directly administered dependency","UTC+7");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CY","Cyprus","Europe","Nicosia","Euro","Greek and Turkish","Church of Cyprus","Unitary presidential constitutional republic","UTC+2(winter)/UTC+3(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("CZ","Czech Republic","Europe","Prague","Czech koruna","Czech","Undeclared/Non-religious","Unitary parliamentary constitutional republic","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("DE","Germany","Europe","Berlin","Euro","German","Christianity","Republic","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("DJ","Djibouti","Africa","Djibouti","Djiboutian franc","French and Arabic","	Sunni Islam","Unitary dominant-party presidential republic","UTC+3");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("DK","Denmark","Europe","Copenhagen","Danish krone","Danish","Church of Denmark","Unitary parliamentary constitutional monarchy","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("DM","Dominica","North America","Roseau","East Caribbean dollar","English","Christianity","Unitary parliamentary republic","UTC–4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("DO","Dominican Republic","North America","Santo Domingo","Peso(DOP)","Spanish","Roman Catholicism","Unitary presidential republic","UTC-4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("DZ","Algeria","Africa","Algiers","Dinar","Arabic and Berber","Islam","Unitary semi-presidential constitutional republic","UTC+1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("EC","Ecuador","South America","Quito","United States dollar","Spanish","Roman Catholic","Unitary presidential constitutional republic","UTC−5");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("EE","Estonia","Europe","Tallinn","Euro","Estonian","Orthodox","Unitary parliamentary republic","UTC+2(winter)/UTC+3(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("EG","Egypt","Africa","Cairo","Egyptian pound","Arabic","Islam","Unitary semi-presidential republic","UTC+2");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("EH","Western Sahara","Africa","Al-Ujun","Moroccan Dirham","Arabic","Islam","Unitary one-party presidential republic","UTC+1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ER","Eritrea","Africa","Asmara","Nakfa","Tigrinya and Arabic","Christianity and Islam","Unitary one-party presidential republic","UTC+3");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ES","Spain","Europe","Madrid","Euro","Spanish","Catholicism","Unitary parliamentary constitutional monarchy","UTC⁠±0 to 2");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ET","Ethiopia","Africa","Addis Ababa","Birr","Amharic","Christianity and Islam","Federal parliamentary constitutional republic","UTC+3");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("FI","Finland","Europe","Helsinki","Euro","Finnish","Evangelical Lutheran Church","Unitary parliamentary republic","UTC+2(winter)/UTC+3(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("FJ","Fiji","Oceania","Suva","Fijian dollar","Fijian and English","Christianity","Unitary parliamentary representative democratic republic","UTC+12(winter)/UTC+13(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("FK","Falkland Islands (Malvinas)","South America","Stanley","Falklands pound","English","Protestantism","Devolved parliamentary dependency","UTC-3");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("FM","Micronesia, Federated States of","Oceania","Palikir","United States dollar","English","Christianity","Federal parliamentary republic","UTC+10/+11");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("FO","Faroe Islands","Europe","Tórshavn","Faroese króna","Faroese and Danish","Church of the Faroe Islands","Constitutional monarchy","UTC+0(winter)/UTC+1(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("FR","France","Europe","Paris","Euro","French","Roman Catholic","Unitary semi-presidential republic","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GA","Gabon","Africa","Libreville","Central African CFA franc","French","Roman Catholicism and Protestantism","Unitary dominant-party presidential republic","UTC+1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GB","United Kingdom","Europe","London","Pound sterling","English","Christianity","Constitutional monarchy","UTC+0(winter)/UTC+1(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GBCHA","Channel Islands","Europe","London","Pound sterling","English","Anglicanism","Constitutional monarchy","UTC+0(winter)/UTC+1(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GD","Grenada","North America", "St. George''s","East Caribbean dollar","English","Protestantism","Unitary two-party parliamentary constitutional monarchy","UTC−4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GE","Georgia","Europe","Tbilisi","Georgian lari","Georgian","Eastern Orthodoxy","Unitary parliamentary constitutional republic","UTC+4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GF","French Guiana","South America","Conakry","Euro","French","Roman Catholicism","Unitary semi-presidential republic","UTC−3");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GG","Guernsey","Europe","Saint Peter Port","Pound sterling and Guernsey pound","English","Church of England","Constitutional monarchy","UTC+0(winter)/UTC+1(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GH","Ghana","Africa","Accra","Ghanaian cedi","English","Christianity","Unitary presidential constitutional republic","UTC+0");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GI","Gibraltar","Europe","Gibraltar","Gibraltar pound","English","Roman Catholicism","Constitutional monarchy","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GL","Greenland","North America","Nuuk","Danish krone","Greenlandic","Church of Greenland","Constitutional monarchy","UTC-4 to 0");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GM","Gambia","Africa","Banjul","Dalasi","English","Islam","Unitary presidential republic","UTC+0");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GN","Guinea","Africa","Conakry","Guinean franc","French","Islam","Unitary presidential republic","UTC+0");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GP","Guadeloupe","North America","Basse-Terre","Euro","French","Roman Catholicism","Unitary semi-presidential republic","UTC-4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GQ","Equatorial Guinea","Africa","Malabo","Central African CFA franc","Spanish, French and Portuguese","Roman Catholicism","Republic","	UTC+1");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GR","Greece","Europe","Athens","Euro","Greek","Eastern Orthodoxy","Unitary parliamentary republic","UTC+2");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GS","South Georgia and the South Sandwich Islands","Antarctica","King Edward Point","Falkland Islands pound","English","-","Constitutional monarchy","UTC-2");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GT","Guatemala","North America","Guatemala City","Quetzal","Spanish","Christianity","Unitary presidential republic","UTC−6");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GU","Guam","Oceania","Hagåtña","United States dollar","English and Chamorro","Roman Catholicism","Devolved presidential constitutional dependency","UTC+10");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GW","Guinea-Bissau","Africa","Bissau","West African CFA franc","Portuguese and Creole","Islam","Unitary semi-presidential republic","UTC+0");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("GY","Guyana","South America","Georgetown","Guyanese dollar","English","Christianity","Unitary presidential constitutional socialist republic","UTC-4");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("HK","Hong Kong","Asia","Hong Kong","Hong Kong dollar","Chinese and English","Shenism","Devolved executive-led system within a socialist republic","UTC+8");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("HM","Heard Island and McDonald Islands","Antarctica","-","Australian dollar","English","-","Federal parliamentary constitutional monarchy","UTC+5");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("HN","Honduras","North America","Tegucigalpa","Lempira","Spanish","Roman Catholicism","Unitary presidential republic","UTC−6");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("HR","Croatia","Europe","Zagreb","Kuna","Croatian","Roman Catholicism","Unitary parliamentary constitutional republic","UTC+1(winter)/UTC+2(summer)");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("HT","Haiti","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("HU","Hungary","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ID","Indonesia","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("IE","Ireland","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("IL","Israel","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("IM","Isle of Man","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("IN","India","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("IO","British Indian Ocean Territory","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("IQ","Iraq","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("IR","Iran, Islamic Republic of Iran","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("IS","Iceland","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("IT","Italy","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("JE","Jersey","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("JM","Jamaica","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("JO","Jordan","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("JP","Japan","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KE","Kenya","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KG","Kyrgyzstan","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KH","Cambodia","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KI","Kiribati","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KM","Comoros","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KN","Saint Kitts and Nevis","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KP","Korea, North","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KR","Korea, South","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KW","Kuwait","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KY","Cayman Islands","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("KZ","Kazakhstan","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LA","Lao People's Democratic Republic","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LB","Lebanon","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LC","Saint Lucia","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LI","Liechtenstein","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LK","Sri Lanka","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LR","Liberia","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LS","Lesotho","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LT","Lithuania","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LU","Luxembourg","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LV","Latvia","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("LY","Libya","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MA","Morocco","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MC","Monaco","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MD","Moldova, Republic of Moldova","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ME","Montenegro","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MF","Saint Martin (French Part)","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MG","Madagascar","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MH","Marshall Islands","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MK","North Macedonia","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ML","Mali","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MM","Myanmar","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MN","Mongolia","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MO","Macao","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MP","Northern Mariana Islands","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MQ","Martinique","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MR","Mauritania","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MS","Montserrat","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MT","Malta","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MU","Mauritius","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MV","Maldives","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MW","Malawi","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MX","Mexico","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MY","Malaysia","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("MZ","Mozambique","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NA","Namibia","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NC","New Caledonia","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NE","Niger","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NF","Norfolk Island","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NG","Nigeria","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NI","Nicaragua","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NL","Netherlands","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NO","Norway","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NP","Nepal","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NR","Nauru","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NU","Niue","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("NZ","New Zealand","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("OM","Oman","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PA","Panama","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PE","Peru","South America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PF","French Polynesia","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PG","Papua New Guinea","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PH","Philippines","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PK","Pakistan","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PL","Poland","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PM","Saint Pierre and Miquelon","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PN","Pitcairn","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PR","Puerto Rico","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PS","Palestinian, State of Palestinian","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PT","Portugal","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PW","Palau","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("PY","Paraguay","South America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("QA","Qatar","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("RE","Reunion","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("RO","Romania","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("RS","Serbia","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("RU","Russian Federation","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("RW","Rwanda","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SA","Saudi Arabia","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SB","Solomon Islands","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SC","Seychelles","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SD","Sudan","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SE","Sweden","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SG","Singapore","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SH","Saint Helena, Ascension and Tristan da Cunha","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SI","Slovenia","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SJ","Svalbard and Jan Mayen","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SK","Slovakia","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SL","Sierra Leone","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SM","San Marino","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SN","Senegal","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SO","Somalia","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SR","Suriname","South America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SS","South Sudan","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ST","Sao Tome and Principe","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SV","El Salvador","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SX","Sint Maarten (Dutch Part)","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SY","Syrian Arab Republic","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("SZ","Swaziland","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TC","Turks and Caicos Islands","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TD","Chad","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TF","French Southern Territories","Antarctica");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TG","Togo","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TH","Thailand","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TJ","Tajikistan","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TK","Tokelau","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TL","Timor-Leste","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TM","Turkmenistan","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TN","Tunisia","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TO","Tonga","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TR","Turkey","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TT","Trinidad and Tobago","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TV","Tuvalu","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TW","Taiwan, Province of China","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("TZ","Tanzania, United Republic of Tanzania","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("UA","Ukraine","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("UG","Uganda","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("UM","United States Minor Outlying Islands","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("US","United States","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("UY","Uruguay","South America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("UZ","Uzbekistan","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("VA","Holy See (Vatican City State)","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("VC","Saint Vincent and the Grenadines","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("VE","Venezuela, Bolivarian Republic of Venezuela","South America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("VG","Virgin Islands, British","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("VI","Virgin Islands, U.S.","North America");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("VN","Viet Nam","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("VU","Vanuatu","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("WF","Wallis and Futuna","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("WS","Samoa","Oceania");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("YE","Yemen","Asia");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("YT","Mayotte","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ZA","South Africa","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ZM","Zambia","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("ZW","Zimbabwe","Africa");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("XK","Kosovo","Europe");
INSERT INTO country(country_code,name,continent,capital,currency,language,religion,political_system,time_zone) VALUES ("DOMESTIC","World","Milky Way");