-- INITIAL DATA ABOUT ALL COUNTRIES"
# INSERT INTO country(country_code,name,continent,currency,language) VALUES ();
INSERT INTO country(country_code,name,continent) VALUES ("AD","Andorra","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("AE","United Arab Emirates","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("AF","Afghanistan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("AG","Antigua and Barbuda","North America");
INSERT INTO country(country_code,name,continent) VALUES ("AI","Anguilla","North America");
INSERT INTO country(country_code,name,continent) VALUES ("AL","Albania","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("AM","Armenia","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("AO","Angola","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("AQ","Antarctica","Antarctica");
INSERT INTO country(country_code,name,continent) VALUES ("AR","Argentina","South America");
INSERT INTO country(country_code,name,continent) VALUES ("AS","American Samoa","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("AT","Austria","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("AU","Australia","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("AW","Aruba","North America");
INSERT INTO country(country_code,name,continent) VALUES ("AX","Aland Islands","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("AZ","Azerbaijan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("BA","Bosnia and Herzegovina","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("BB","Barbados","North America");
INSERT INTO country(country_code,name,continent) VALUES ("BD","Bangladesh","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("BE","Belgium","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("BF","Burkina Faso","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("BG","Bulgaria","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("BH","Bahrain","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("BI","Burundi","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("BJ","Benin","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("BL","Saint Barthelemy","North America");
INSERT INTO country(country_code,name,continent) VALUES ("BM","Bermuda","North America");
INSERT INTO country(country_code,name,continent) VALUES ("BN","Brunei Darussalam","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("BO","Bolivia, Plurinational State of Bolivia","South America");
INSERT INTO country(country_code,name,continent) VALUES ("BQ","Bonaire, Sint Eustatius and Saba","North America");
INSERT INTO country(country_code,name,continent) VALUES ("BR","Brazil","South America");
INSERT INTO country(country_code,name,continent) VALUES ("BS","Bahamas","North America");
INSERT INTO country(country_code,name,continent) VALUES ("BT","Bhutan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("BV","Bouvet Island","Antarctica");
INSERT INTO country(country_code,name,continent) VALUES ("BW","Botswana","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("BY","Belarus","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("BZ","Belize","North America");
INSERT INTO country(country_code,name,continent) VALUES ("CA","Canada","North America");
INSERT INTO country(country_code,name,continent) VALUES ("CC","Cocos (Keeling) Islands","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("CD","Congo, the Democratic Republic of the Congo","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("CF","Central African Republic","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("CG","Congo","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("CH","Switzerland","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("CI","Cote d'Ivoire","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("CK","Cook Islands","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("CL","Chile","South America");
INSERT INTO country(country_code,name,continent) VALUES ("CM","Cameroon","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("CN","China","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("CO","Colombia","South America");
INSERT INTO country(country_code,name,continent) VALUES ("CR","Costa Rica","North America");
INSERT INTO country(country_code,name,continent) VALUES ("CU","Cuba","North America");
INSERT INTO country(country_code,name,continent) VALUES ("CV","Cape Verde","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("CW","Curacao","North America");
INSERT INTO country(country_code,name,continent) VALUES ("CX","Christmas Island","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("CY","Cyprus","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("CZ","Czech Republic","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("DE","Germany","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("DJ","Djibouti","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("DK","Denmark","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("DM","Dominica","North America");
INSERT INTO country(country_code,name,continent) VALUES ("DO","Dominican Republic","North America");
INSERT INTO country(country_code,name,continent) VALUES ("DZ","Algeria","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("EC","Ecuador","South America");
INSERT INTO country(country_code,name,continent) VALUES ("EE","Estonia","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("EG","Egypt","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("EH","Western Sahara","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("ER","Eritrea","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("ES","Spain","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("ET","Ethiopia","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("FI","Finland","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("FJ","Fiji","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("FK","Falkland Islands (Malvinas)","South America");
INSERT INTO country(country_code,name,continent) VALUES ("FM","Micronesia, Federated States of","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("FO","Faroe Islands","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("FR","France","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("GA","Gabon","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("GB","United Kingdom","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("GBCHA","Channel Islands","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("GD","Grenada","North America");
INSERT INTO country(country_code,name,continent) VALUES ("GE","Georgia","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("GF","French Guiana","South America");
INSERT INTO country(country_code,name,continent) VALUES ("GG","Guernsey","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("GH","Ghana","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("GI","Gibraltar","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("GL","Greenland","North America");
INSERT INTO country(country_code,name,continent) VALUES ("GM","Gambia","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("GN","Guinea","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("GP","Guadeloupe","North America");
INSERT INTO country(country_code,name,continent) VALUES ("GQ","Equatorial Guinea","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("GR","Greece","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("GS","South Georgia and the South Sandwich Islands","Antarctica");
INSERT INTO country(country_code,name,continent) VALUES ("GT","Guatemala","North America");
INSERT INTO country(country_code,name,continent) VALUES ("GU","Guam","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("GW","Guinea-Bissau","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("GY","Guyana","South America");
INSERT INTO country(country_code,name,continent) VALUES ("HK","Hong Kong","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("HM","Heard Island and McDonald Islands","Antarctica");
INSERT INTO country(country_code,name,continent) VALUES ("HN","Honduras","North America");
INSERT INTO country(country_code,name,continent) VALUES ("HR","Croatia","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("HT","Haiti","North America");
INSERT INTO country(country_code,name,continent) VALUES ("HU","Hungary","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("ID","Indonesia","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("IE","Ireland","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("IL","Israel","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("IM","Isle of Man","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("IN","India","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("IO","British Indian Ocean Territory","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("IQ","Iraq","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("IR","Iran, Islamic Republic of Iran","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("IS","Iceland","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("IT","Italy","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("JE","Jersey","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("JM","Jamaica","North America");
INSERT INTO country(country_code,name,continent) VALUES ("JO","Jordan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("JP","Japan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("KE","Kenya","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("KG","Kyrgyzstan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("KH","Cambodia","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("KI","Kiribati","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("KM","Comoros","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("KN","Saint Kitts and Nevis","North America");
INSERT INTO country(country_code,name,continent) VALUES ("KP","Korea, North","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("KR","Korea, South","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("KW","Kuwait","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("KY","Cayman Islands","North America");
INSERT INTO country(country_code,name,continent) VALUES ("KZ","Kazakhstan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("LA","Lao People's Democratic Republic","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("LB","Lebanon","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("LC","Saint Lucia","North America");
INSERT INTO country(country_code,name,continent) VALUES ("LI","Liechtenstein","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("LK","Sri Lanka","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("LR","Liberia","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("LS","Lesotho","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("LT","Lithuania","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("LU","Luxembourg","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("LV","Latvia","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("LY","Libya","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("MA","Morocco","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("MC","Monaco","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("MD","Moldova, Republic of Moldova","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("ME","Montenegro","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("MF","Saint Martin (French Part)","North America");
INSERT INTO country(country_code,name,continent) VALUES ("MG","Madagascar","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("MH","Marshall Islands","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("MK","North Macedonia","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("ML","Mali","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("MM","Myanmar","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("MN","Mongolia","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("MO","Macao","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("MP","Northern Mariana Islands","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("MQ","Martinique","North America");
INSERT INTO country(country_code,name,continent) VALUES ("MR","Mauritania","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("MS","Montserrat","North America");
INSERT INTO country(country_code,name,continent) VALUES ("MT","Malta","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("MU","Mauritius","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("MV","Maldives","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("MW","Malawi","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("MX","Mexico","North America");
INSERT INTO country(country_code,name,continent) VALUES ("MY","Malaysia","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("MZ","Mozambique","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("NA","Namibia","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("NC","New Caledonia","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("NE","Niger","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("NF","Norfolk Island","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("NG","Nigeria","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("NI","Nicaragua","North America");
INSERT INTO country(country_code,name,continent) VALUES ("NL","Netherlands","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("NO","Norway","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("NP","Nepal","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("NR","Nauru","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("NU","Niue","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("NZ","New Zealand","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("OM","Oman","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("PA","Panama","North America");
INSERT INTO country(country_code,name,continent) VALUES ("PE","Peru","South America");
INSERT INTO country(country_code,name,continent) VALUES ("PF","French Polynesia","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("PG","Papua New Guinea","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("PH","Philippines","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("PK","Pakistan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("PL","Poland","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("PM","Saint Pierre and Miquelon","North America");
INSERT INTO country(country_code,name,continent) VALUES ("PN","Pitcairn","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("PR","Puerto Rico","North America");
INSERT INTO country(country_code,name,continent) VALUES ("PS","Palestinian, State of Palestinian","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("PT","Portugal","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("PW","Palau","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("PY","Paraguay","South America");
INSERT INTO country(country_code,name,continent) VALUES ("QA","Qatar","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("RE","Reunion","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("RO","Romania","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("RS","Serbia","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("RU","Russian Federation","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("RW","Rwanda","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("SA","Saudi Arabia","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("SB","Solomon Islands","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("SC","Seychelles","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("SD","Sudan","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("SE","Sweden","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("SG","Singapore","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("SH","Saint Helena, Ascension and Tristan da Cunha","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("SI","Slovenia","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("SJ","Svalbard and Jan Mayen","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("SK","Slovakia","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("SL","Sierra Leone","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("SM","San Marino","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("SN","Senegal","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("SO","Somalia","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("SR","Suriname","South America");
INSERT INTO country(country_code,name,continent) VALUES ("SS","South Sudan","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("ST","Sao Tome and Principe","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("SV","El Salvador","North America");
INSERT INTO country(country_code,name,continent) VALUES ("SX","Sint Maarten (Dutch Part)","North America");
INSERT INTO country(country_code,name,continent) VALUES ("SY","Syrian Arab Republic","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("SZ","Swaziland","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("TC","Turks and Caicos Islands","North America");
INSERT INTO country(country_code,name,continent) VALUES ("TD","Chad","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("TF","French Southern Territories","Antarctica");
INSERT INTO country(country_code,name,continent) VALUES ("TG","Togo","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("TH","Thailand","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("TJ","Tajikistan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("TK","Tokelau","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("TL","Timor-Leste","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("TM","Turkmenistan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("TN","Tunisia","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("TO","Tonga","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("TR","Turkey","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("TT","Trinidad and Tobago","North America");
INSERT INTO country(country_code,name,continent) VALUES ("TV","Tuvalu","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("TW","Taiwan, Province of China","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("TZ","Tanzania, United Republic of Tanzania","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("UA","Ukraine","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("UG","Uganda","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("UM","United States Minor Outlying Islands","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("US","United States","North America");
INSERT INTO country(country_code,name,continent) VALUES ("UY","Uruguay","South America");
INSERT INTO country(country_code,name,continent) VALUES ("UZ","Uzbekistan","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("VA","Holy See (Vatican City State)","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("VC","Saint Vincent and the Grenadines","North America");
INSERT INTO country(country_code,name,continent) VALUES ("VE","Venezuela, Bolivarian Republic of Venezuela","South America");
INSERT INTO country(country_code,name,continent) VALUES ("VG","Virgin Islands, British","North America");
INSERT INTO country(country_code,name,continent) VALUES ("VI","Virgin Islands, U.S.","North America");
INSERT INTO country(country_code,name,continent) VALUES ("VN","Viet Nam","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("VU","Vanuatu","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("WF","Wallis and Futuna","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("WS","Samoa","Oceania");
INSERT INTO country(country_code,name,continent) VALUES ("YE","Yemen","Asia");
INSERT INTO country(country_code,name,continent) VALUES ("YT","Mayotte","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("ZA","South Africa","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("ZM","Zambia","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("ZW","Zimbabwe","Africa");
INSERT INTO country(country_code,name,continent) VALUES ("XK","Kosovo","Europe");
INSERT INTO country(country_code,name,continent) VALUES ("DOMESTIC","World","Milky Way");